# Import statement
import os

# Get the directory path of the current file
dir_path = os.path.dirname(os.path.realpath(__file__))

# Set the project path to the current directory path
project_path = dir_path

# The actual configuration file path will be generated by formatting this string with the database name
config_file_path = project_path + '/config/{}_config.txt'
